### ISSUE TITLE
install instructions fail

### ISSUE THREAD

**Issue by rdp** [ninjudd/drip#79]
Hello, the readme install instructions say to do this:

 curl -L http://drip.flatland.org > ~/bin/drip

which doesn't work, FWIW...

**Comment by avindra** [comment]
Also getting a connection timeout several months later... can you rehost it somewhere more reliable?

**Comment by amalloy** [comment]
I don't know specifically what @ninjudd hosted at drip.flatland.org, but using ˜https://raw.githubusercontent.com/ninjudd/drip/master/bin/drip instead works fine. I'll update the readme.

**Comment by ninjudd** [comment]
It was just a redirect to that.
